### ISSUE TITLE
'Host Game' doesn't work

### ISSUE THREAD

**Issue by Jusonex** [sbx320/mtasa-blue#1]
...because the 'Host Game' functionality tries to load the client's lua5.1.dll (which fails because the API_CHECK is available)

In the old project, lua5.1c is not built at all.

**Comment by ccw808** [comment]
Fix is to change `vendor\lua\premake5.lua` **targetname** to "_lua5.1c_"

The old project didn't have a Lua dll for the client because it included the lua src in the Client Deathmatch project. (To make it harder for hackers.)
